global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'spark_job'
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
